// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsnqhyaafxsupfndxdah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzbnFoeWFhZnhzdXBmbmR4ZGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDc5ODUsImV4cCI6MjA3MTI4Mzk4NX0.3VBgVLkeKIntyUYUllyqJSCOJi2QbLuVHpSs5wnlSi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});